# cargo-features = ["edition2021"]
[package]
name = "slice"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
cc = "1.0"

[dependencies]

libc = "0.2"
cc = "1.0"
